import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Mobilenav from "@/components/Navbarcomponent/Mobilenav";
import HotelFooter from "@/components/Footercomponents/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          {children}
          <HotelFooter />
          <Mobilenav />
        </Providers>
      </body>
    </html>
  );
}
